= WebEngineering

**In this repository you can find the materials for the course _Web Engineering_ of the http://www.teko.ch/[TEKO Swiss Technical College] headed by https://github.com/McPringle[Marcus Fihlon].**

This repository contains the workbook including the example code in http://asciidoctor.org/[Asciidoctor] syntax. Of course, you won't find any assessments or solutions for assessments in this repository! Please feel free to correct errors and send me a pull request, I'll thankfully merge it as fast as possible.

== Build the Workbook

If you want to build the workbook you must have http://asciidoctor.org/[Asciidoctor] installed and cloned (or downloaded) this repository. Then simply execute the build script in the top level project folder:

```
./build
```

After the build is successfully finished, you have two new files in the `out` directory. You can open the HTML file in your web browser and the PDF file is for ebook readers and printing.

_Keep on learning! +
Good luck!_
